# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\infer_dialog\openTrainToolDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_openTrainToolDialog(object):
    def setupUi(self, openTrainToolDialog):
        openTrainToolDialog.setObjectName("openTrainToolDialog")
        openTrainToolDialog.resize(385, 116)
        self.verticalLayout = QtWidgets.QVBoxLayout(openTrainToolDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.trainSetLabel_5 = BodyLabel(openTrainToolDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainSetLabel_5.sizePolicy().hasHeightForWidth())
        self.trainSetLabel_5.setSizePolicy(sizePolicy)
        self.trainSetLabel_5.setMinimumSize(QtCore.QSize(150, 0))
        self.trainSetLabel_5.setObjectName("trainSetLabel_5")
        self.horizontalLayout_22.addWidget(self.trainSetLabel_5)
        self.line_23 = QtWidgets.QFrame(openTrainToolDialog)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_22.addWidget(self.line_23)
        self.selectGPUCb = ComboBox(openTrainToolDialog)
        self.selectGPUCb.setObjectName("selectGPUCb")
        self.horizontalLayout_22.addWidget(self.selectGPUCb)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.startPb = PrimaryPushButton(openTrainToolDialog)
        self.startPb.setObjectName("startPb")
        self.verticalLayout.addWidget(self.startPb)

        self.retranslateUi(openTrainToolDialog)
        QtCore.QMetaObject.connectSlotsByName(openTrainToolDialog)

    def retranslateUi(self, openTrainToolDialog):
        _translate = QtCore.QCoreApplication.translate
        openTrainToolDialog.setWindowTitle(_translate("openTrainToolDialog", "open Train Tool"))
        self.trainSetLabel_5.setText(_translate("openTrainToolDialog", "Select GPU"))
        self.startPb.setText(_translate("openTrainToolDialog", "Open"))
from qfluentwidgets import BodyLabel, ComboBox, PrimaryPushButton
