# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\common_dialog\jl1FreeXYZTilesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_freeXYZDialog(object):
    def setupUi(self, freeXYZDialog):
        freeXYZDialog.setObjectName("freeXYZDialog")
        freeXYZDialog.resize(431, 388)
        self.verticalLayout = QtWidgets.QVBoxLayout(freeXYZDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_3 = BodyLabel(freeXYZDialog)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout.addWidget(self.BodyLabel_3)
        self.intoWeb = PushButton(freeXYZDialog)
        self.intoWeb.setObjectName("intoWeb")
        self.horizontalLayout.addWidget(self.intoWeb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BodyLabel_4 = BodyLabel(freeXYZDialog)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout_3.addWidget(self.BodyLabel_4)
        self.tkLE = LineEdit(freeXYZDialog)
        self.tkLE.setObjectName("tkLE")
        self.horizontalLayout_3.addWidget(self.tkLE)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listView = ListView(freeXYZDialog)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.runPB = PushButton(freeXYZDialog)
        self.runPB.setObjectName("runPB")
        self.horizontalLayout_2.addWidget(self.runPB)
        self.cancelPB = PushButton(freeXYZDialog)
        self.cancelPB.setObjectName("cancelPB")
        self.horizontalLayout_2.addWidget(self.cancelPB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(freeXYZDialog)
        QtCore.QMetaObject.connectSlotsByName(freeXYZDialog)

    def retranslateUi(self, freeXYZDialog):
        _translate = QtCore.QCoreApplication.translate
        freeXYZDialog.setWindowTitle(_translate("freeXYZDialog", "Free Online Base Map in JL-1"))
        self.BodyLabel_3.setText(_translate("freeXYZDialog", "Click the button to get free TK"))
        self.intoWeb.setText(_translate("freeXYZDialog", "Click me"))
        self.BodyLabel_4.setText(_translate("freeXYZDialog", "TK"))
        self.runPB.setText(_translate("freeXYZDialog", "OK"))
        self.cancelPB.setText(_translate("freeXYZDialog", "Cancel"))
from qfluentwidgets import BodyLabel, LineEdit, ListView, PushButton
