# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\common_dialog\openXYZTilesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_openXYZTilesDialog(object):
    def setupUi(self, openXYZTilesDialog):
        openXYZTilesDialog.setObjectName("openXYZTilesDialog")
        openXYZTilesDialog.resize(558, 205)
        self.verticalLayout = QtWidgets.QVBoxLayout(openXYZTilesDialog)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 7)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_4 = CardWidget(openXYZTilesDialog)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel = BodyLabel(self.CardWidget_4)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_5.addWidget(self.BodyLabel)
        self.layerNameLE = LineEdit(self.CardWidget_4)
        self.layerNameLE.setObjectName("layerNameLE")
        self.horizontalLayout_5.addWidget(self.layerNameLE)
        self.verticalLayout.addWidget(self.CardWidget_4)
        self.CardWidget_2 = CardWidget(openXYZTilesDialog)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CardWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        self.xyzPathLE = LineEdit(self.CardWidget_2)
        self.xyzPathLE.setObjectName("xyzPathLE")
        self.horizontalLayout_2.addWidget(self.xyzPathLE)
        self.verticalLayout.addWidget(self.CardWidget_2)
        self.runPB = PushButton(openXYZTilesDialog)
        self.runPB.setObjectName("runPB")
        self.verticalLayout.addWidget(self.runPB)

        self.retranslateUi(openXYZTilesDialog)
        QtCore.QMetaObject.connectSlotsByName(openXYZTilesDialog)

    def retranslateUi(self, openXYZTilesDialog):
        _translate = QtCore.QCoreApplication.translate
        openXYZTilesDialog.setWindowTitle(_translate("openXYZTilesDialog", "Add XYZ Tile Parameter Settings"))
        self.BodyLabel.setText(_translate("openXYZTilesDialog", "Please Enter Layer Name"))
        self.BodyLabel_2.setText(_translate("openXYZTilesDialog", "Please Enter XYZ Tile Address"))
        self.runPB.setText(_translate("openXYZTilesDialog", "OK"))
from qfluentwidgets import BodyLabel, CardWidget, LineEdit, PushButton
