# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\addDetectionTypeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetectionType(object):
    def setupUi(self, DetectionType):
        DetectionType.setObjectName("DetectionType")
        DetectionType.resize(409, 235)
        self.verticalLayout = QtWidgets.QVBoxLayout(DetectionType)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel = BodyLabel(DetectionType)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        self.selectI = ComboBox(DetectionType)
        self.selectI.setObjectName("selectI")
        self.horizontalLayout.addWidget(self.selectI)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(DetectionType)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        self.selectII = ComboBox(DetectionType)
        self.selectII.setObjectName("selectII")
        self.horizontalLayout_2.addWidget(self.selectII)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.diyCheckBox = CheckBox(DetectionType)
        self.diyCheckBox.setObjectName("diyCheckBox")
        self.horizontalLayout_5.addWidget(self.diyCheckBox)
        self.diyLineEdit = LineEdit(DetectionType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diyLineEdit.sizePolicy().hasHeightForWidth())
        self.diyLineEdit.setSizePolicy(sizePolicy)
        self.diyLineEdit.setMaxLength(10)
        self.diyLineEdit.setPlaceholderText("")
        self.diyLineEdit.setObjectName("diyLineEdit")
        self.horizontalLayout_5.addWidget(self.diyLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saAdd = PushButton(DetectionType)
        self.saAdd.setObjectName("saAdd")
        self.horizontalLayout_4.addWidget(self.saAdd)
        self.saCancel = PushButton(DetectionType)
        self.saCancel.setObjectName("saCancel")
        self.horizontalLayout_4.addWidget(self.saCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(DetectionType)
        QtCore.QMetaObject.connectSlotsByName(DetectionType)

    def retranslateUi(self, DetectionType):
        _translate = QtCore.QCoreApplication.translate
        DetectionType.setWindowTitle(_translate("DetectionType", "Select Type"))
        self.BodyLabel.setText(_translate("DetectionType", "Level I"))
        self.BodyLabel_2.setText(_translate("DetectionType", "Level II"))
        self.diyCheckBox.setText(_translate("DetectionType", "Diy Type"))
        self.saAdd.setText(_translate("DetectionType", "OK"))
        self.saCancel.setText(_translate("DetectionType", "Cancel"))
from qfluentwidgets import BodyLabel, CheckBox, ComboBox, LineEdit, PushButton
