# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\addSegmentTypeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SegmentType(object):
    def setupUi(self, SegmentType):
        SegmentType.setObjectName("SegmentType")
        SegmentType.resize(464, 251)
        self.verticalLayout = QtWidgets.QVBoxLayout(SegmentType)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel = BodyLabel(SegmentType)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        self.selectI = ComboBox(SegmentType)
        self.selectI.setObjectName("selectI")
        self.horizontalLayout.addWidget(self.selectI)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(SegmentType)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        self.selectII = ComboBox(SegmentType)
        self.selectII.setObjectName("selectII")
        self.horizontalLayout_2.addWidget(self.selectII)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BodyLabel_3 = BodyLabel(SegmentType)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_3.addWidget(self.BodyLabel_3)
        self.selectIII = ComboBox(SegmentType)
        self.selectIII.setObjectName("selectIII")
        self.horizontalLayout_3.addWidget(self.selectIII)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.diyCheckBox = CheckBox(SegmentType)
        self.diyCheckBox.setObjectName("diyCheckBox")
        self.horizontalLayout_5.addWidget(self.diyCheckBox)
        self.diyLineEdit = LineEdit(SegmentType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diyLineEdit.sizePolicy().hasHeightForWidth())
        self.diyLineEdit.setSizePolicy(sizePolicy)
        self.diyLineEdit.setMaxLength(10)
        self.diyLineEdit.setPlaceholderText("")
        self.diyLineEdit.setObjectName("diyLineEdit")
        self.horizontalLayout_5.addWidget(self.diyLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saAdd = PushButton(SegmentType)
        self.saAdd.setObjectName("saAdd")
        self.horizontalLayout_4.addWidget(self.saAdd)
        self.saCancel = PushButton(SegmentType)
        self.saCancel.setObjectName("saCancel")
        self.horizontalLayout_4.addWidget(self.saCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(SegmentType)
        QtCore.QMetaObject.connectSlotsByName(SegmentType)

    def retranslateUi(self, SegmentType):
        _translate = QtCore.QCoreApplication.translate
        SegmentType.setWindowTitle(_translate("SegmentType", "Select Type"))
        self.BodyLabel.setText(_translate("SegmentType", "Level I"))
        self.BodyLabel_2.setText(_translate("SegmentType", "Level II"))
        self.BodyLabel_3.setText(_translate("SegmentType", "Level III"))
        self.diyCheckBox.setText(_translate("SegmentType", "Diy Type"))
        self.saAdd.setText(_translate("SegmentType", "OK"))
        self.saCancel.setText(_translate("SegmentType", "Cancel"))
from qfluentwidgets import BodyLabel, CheckBox, ComboBox, LineEdit, PushButton
