# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\attrEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_attrEditDialog(object):
    def setupUi(self, attrEditDialog):
        attrEditDialog.setObjectName("attrEditDialog")
        attrEditDialog.resize(493, 476)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        attrEditDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(attrEditDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SubtitleLabel = SubtitleLabel(attrEditDialog)
        self.SubtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout.addWidget(self.SubtitleLabel)
        self.shpSingleRenderScrollArea = QtWidgets.QScrollArea(attrEditDialog)
        self.shpSingleRenderScrollArea.setWidgetResizable(True)
        self.shpSingleRenderScrollArea.setObjectName("shpSingleRenderScrollArea")
        self.ScrollAreaWidget = QtWidgets.QWidget()
        self.ScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 473, 380))
        self.ScrollAreaWidget.setObjectName("ScrollAreaWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ScrollAreaWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shpSingleRenderScrollArea.setWidget(self.ScrollAreaWidget)
        self.verticalLayout.addWidget(self.shpSingleRenderScrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okPushButton = PushButton(attrEditDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = PushButton(attrEditDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(attrEditDialog)
        QtCore.QMetaObject.connectSlotsByName(attrEditDialog)

    def retranslateUi(self, attrEditDialog):
        _translate = QtCore.QCoreApplication.translate
        attrEditDialog.setWindowTitle(_translate("attrEditDialog", "Mapping"))
        self.SubtitleLabel.setText(_translate("attrEditDialog", "属性填写(Attribute Editing)"))
        self.okPushButton.setText(_translate("attrEditDialog", "确定(Space)"))
        self.okPushButton.setShortcut(_translate("attrEditDialog", "Space"))
        self.cancelPushButton.setText(_translate("attrEditDialog", "取消(Esc)"))
        self.cancelPushButton.setShortcut(_translate("attrEditDialog", "Ctrl+S"))
from qfluentwidgets import PushButton, SubtitleLabel
import yoyirs_rc
