# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\pixelClassifyMapDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pixelClassifyMapDialog(object):
    def setupUi(self, pixelClassifyMapDialog):
        pixelClassifyMapDialog.setObjectName("pixelClassifyMapDialog")
        pixelClassifyMapDialog.resize(654, 421)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pixelClassifyMapDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(pixelClassifyMapDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SubtitleLabel = SubtitleLabel(pixelClassifyMapDialog)
        self.SubtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout.addWidget(self.SubtitleLabel)
        self.shpSingleRenderScrollArea = QtWidgets.QScrollArea(pixelClassifyMapDialog)
        self.shpSingleRenderScrollArea.setWidgetResizable(True)
        self.shpSingleRenderScrollArea.setObjectName("shpSingleRenderScrollArea")
        self.ScrollAreaWidget = QtWidgets.QWidget()
        self.ScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 634, 327))
        self.ScrollAreaWidget.setObjectName("ScrollAreaWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ScrollAreaWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bgLayout = QtWidgets.QHBoxLayout()
        self.bgLayout.setObjectName("bgLayout")
        self.bgSpinBox = SpinBox(self.ScrollAreaWidget)
        self.bgSpinBox.setMinimum(-65536)
        self.bgSpinBox.setMaximum(65536)
        self.bgSpinBox.setObjectName("bgSpinBox")
        self.bgLayout.addWidget(self.bgSpinBox)
        self.bgClassifyName = BodyLabel(self.ScrollAreaWidget)
        self.bgClassifyName.setObjectName("bgClassifyName")
        self.bgLayout.addWidget(self.bgClassifyName)
        self.verticalLayout_2.addLayout(self.bgLayout)
        self.shpSingleRenderScrollArea.setWidget(self.ScrollAreaWidget)
        self.verticalLayout.addWidget(self.shpSingleRenderScrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okPushButton = PushButton(pixelClassifyMapDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.cancelPushButton = PushButton(pixelClassifyMapDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(pixelClassifyMapDialog)
        QtCore.QMetaObject.connectSlotsByName(pixelClassifyMapDialog)

    def retranslateUi(self, pixelClassifyMapDialog):
        _translate = QtCore.QCoreApplication.translate
        pixelClassifyMapDialog.setWindowTitle(_translate("pixelClassifyMapDialog", "Mapping"))
        self.SubtitleLabel.setText(_translate("pixelClassifyMapDialog", "Pixel Classify Mapping"))
        self.bgClassifyName.setText(_translate("pixelClassifyMapDialog", "Background Pixel"))
        self.okPushButton.setText(_translate("pixelClassifyMapDialog", "OK"))
        self.cancelPushButton.setText(_translate("pixelClassifyMapDialog", "Cancel"))
from qfluentwidgets import BodyLabel, PushButton, SpinBox, SubtitleLabel
import yoyirs_rc
