# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\shpLabelingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shpLabelingDialog(object):
    def setupUi(self, shpLabelingDialog):
        shpLabelingDialog.setObjectName("shpLabelingDialog")
        shpLabelingDialog.resize(541, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(shpLabelingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openLabelingChb = CheckBox(shpLabelingDialog)
        self.openLabelingChb.setObjectName("openLabelingChb")
        self.horizontalLayout.addWidget(self.openLabelingChb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(shpLabelingDialog)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        self.labelingFieldCb = ComboBox(shpLabelingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelingFieldCb.sizePolicy().hasHeightForWidth())
        self.labelingFieldCb.setSizePolicy(sizePolicy)
        self.labelingFieldCb.setObjectName("labelingFieldCb")
        self.horizontalLayout_2.addWidget(self.labelingFieldCb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BodyLabel_3 = BodyLabel(shpLabelingDialog)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_3.addWidget(self.BodyLabel_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BodyLabel_4 = BodyLabel(shpLabelingDialog)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout_4.addWidget(self.BodyLabel_4)
        self.fontSizeSpinBox = SpinBox(shpLabelingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontSizeSpinBox.sizePolicy().hasHeightForWidth())
        self.fontSizeSpinBox.setSizePolicy(sizePolicy)
        self.fontSizeSpinBox.setMaximum(100)
        self.fontSizeSpinBox.setProperty("value", 15)
        self.fontSizeSpinBox.setObjectName("fontSizeSpinBox")
        self.horizontalLayout_4.addWidget(self.fontSizeSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.saOk = PushButton(shpLabelingDialog)
        self.saOk.setObjectName("saOk")
        self.horizontalLayout_9.addWidget(self.saOk)
        self.saCancel = PushButton(shpLabelingDialog)
        self.saCancel.setObjectName("saCancel")
        self.horizontalLayout_9.addWidget(self.saCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_9)

        self.retranslateUi(shpLabelingDialog)
        QtCore.QMetaObject.connectSlotsByName(shpLabelingDialog)

    def retranslateUi(self, shpLabelingDialog):
        _translate = QtCore.QCoreApplication.translate
        shpLabelingDialog.setWindowTitle(_translate("shpLabelingDialog", "Labeling Dialog"))
        self.openLabelingChb.setText(_translate("shpLabelingDialog", "Open Labeling"))
        self.BodyLabel_2.setText(_translate("shpLabelingDialog", "labeling field"))
        self.BodyLabel_3.setText(_translate("shpLabelingDialog", "labeling color"))
        self.BodyLabel_4.setText(_translate("shpLabelingDialog", "font size"))
        self.saOk.setText(_translate("shpLabelingDialog", "Ok"))
        self.saCancel.setText(_translate("shpLabelingDialog", "Cancel"))
from qfluentwidgets import BodyLabel, CheckBox, ComboBox, PushButton, SpinBox
