# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\spectralCurveDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spectralCurveDialog(object):
    def setupUi(self, spectralCurveDialog):
        spectralCurveDialog.setObjectName("spectralCurveDialog")
        spectralCurveDialog.resize(673, 473)
        self.verticalLayout = QtWidgets.QVBoxLayout(spectralCurveDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.clearPointsPb = PrimaryPushButton(spectralCurveDialog)
        self.clearPointsPb.setObjectName("clearPointsPb")
        self.gridLayout_5.addWidget(self.clearPointsPb, 0, 2, 1, 1)
        self.collectionModePb = PillPushButton(spectralCurveDialog)
        self.collectionModePb.setChecked(False)
        self.collectionModePb.setObjectName("collectionModePb")
        self.gridLayout_5.addWidget(self.collectionModePb, 0, 1, 1, 1)
        self.startCollectPb = PrimaryPushButton(spectralCurveDialog)
        self.startCollectPb.setObjectName("startCollectPb")
        self.gridLayout_5.addWidget(self.startCollectPb, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chartLayout = QtWidgets.QGridLayout()
        self.chartLayout.setObjectName("chartLayout")
        self.horizontalLayout_2.addLayout(self.chartLayout)
        self.ListView = ListView(spectralCurveDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListView.sizePolicy().hasHeightForWidth())
        self.ListView.setSizePolicy(sizePolicy)
        self.ListView.setObjectName("ListView")
        self.horizontalLayout_2.addWidget(self.ListView)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(spectralCurveDialog)
        QtCore.QMetaObject.connectSlotsByName(spectralCurveDialog)

    def retranslateUi(self, spectralCurveDialog):
        _translate = QtCore.QCoreApplication.translate
        spectralCurveDialog.setWindowTitle(_translate("spectralCurveDialog", "Spectral Curve Check"))
        self.clearPointsPb.setText(_translate("spectralCurveDialog", "Clear point"))
        self.collectionModePb.setText(_translate("spectralCurveDialog", "Collection Mode"))
        self.startCollectPb.setText(_translate("spectralCurveDialog", "Start Collect"))
from qfluentwidgets import ListView, PillPushButton, PrimaryPushButton
