# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\web_selectRejectReason.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_web_selectRejectReasonDialog(object):
    def setupUi(self, web_selectRejectReasonDialog):
        web_selectRejectReasonDialog.setObjectName("web_selectRejectReasonDialog")
        web_selectRejectReasonDialog.resize(449, 236)
        self.verticalLayout = QtWidgets.QVBoxLayout(web_selectRejectReasonDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.BodyLabel = BodyLabel(web_selectRejectReasonDialog)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_22.addWidget(self.BodyLabel)
        self.reasonLE = LineEdit(web_selectRejectReasonDialog)
        self.reasonLE.setMaxLength(40)
        self.reasonLE.setObjectName("reasonLE")
        self.horizontalLayout_22.addWidget(self.reasonLE)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.missCb = CheckBox(web_selectRejectReasonDialog)
        self.missCb.setChecked(True)
        self.missCb.setObjectName("missCb")
        self.horizontalLayout_24.addWidget(self.missCb)
        self.faultCb = CheckBox(web_selectRejectReasonDialog)
        self.faultCb.setObjectName("faultCb")
        self.horizontalLayout_24.addWidget(self.faultCb)
        self.trimCb = CheckBox(web_selectRejectReasonDialog)
        self.trimCb.setObjectName("trimCb")
        self.horizontalLayout_24.addWidget(self.trimCb)
        self.classFaultCb = CheckBox(web_selectRejectReasonDialog)
        self.classFaultCb.setObjectName("classFaultCb")
        self.horizontalLayout_24.addWidget(self.classFaultCb)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.okPb = PrimaryPushButton(web_selectRejectReasonDialog)
        self.okPb.setObjectName("okPb")
        self.horizontalLayout_23.addWidget(self.okPb)
        self.cancelPb = PrimaryPushButton(web_selectRejectReasonDialog)
        self.cancelPb.setObjectName("cancelPb")
        self.horizontalLayout_23.addWidget(self.cancelPb)
        self.verticalLayout.addLayout(self.horizontalLayout_23)

        self.retranslateUi(web_selectRejectReasonDialog)
        QtCore.QMetaObject.connectSlotsByName(web_selectRejectReasonDialog)

    def retranslateUi(self, web_selectRejectReasonDialog):
        _translate = QtCore.QCoreApplication.translate
        web_selectRejectReasonDialog.setWindowTitle(_translate("web_selectRejectReasonDialog", "选择驳回原因"))
        self.BodyLabel.setText(_translate("web_selectRejectReasonDialog", "驳回原因:"))
        self.missCb.setText(_translate("web_selectRejectReasonDialog", "目标遗漏"))
        self.faultCb.setText(_translate("web_selectRejectReasonDialog", "错误删除"))
        self.trimCb.setText(_translate("web_selectRejectReasonDialog", "修整边界"))
        self.classFaultCb.setText(_translate("web_selectRejectReasonDialog", "类别错误"))
        self.okPb.setText(_translate("web_selectRejectReasonDialog", "确定(Space)"))
        self.okPb.setShortcut(_translate("web_selectRejectReasonDialog", "Space"))
        self.cancelPb.setText(_translate("web_selectRejectReasonDialog", "取消驳回(Esc)"))
        self.cancelPb.setShortcut(_translate("web_selectRejectReasonDialog", "Esc"))
from qfluentwidgets import BodyLabel, CheckBox, LineEdit, PrimaryPushButton
