# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\web_inputBookmarkNameDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_web_inputBookmarkNameDialog(object):
    def setupUi(self, web_inputBookmarkNameDialog):
        web_inputBookmarkNameDialog.setObjectName("web_inputBookmarkNameDialog")
        web_inputBookmarkNameDialog.resize(428, 136)
        self.verticalLayout = QtWidgets.QVBoxLayout(web_inputBookmarkNameDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.BodyLabel = BodyLabel(web_inputBookmarkNameDialog)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_22.addWidget(self.BodyLabel)
        self.bookmarkNameLE = LineEdit(web_inputBookmarkNameDialog)
        self.bookmarkNameLE.setMaxLength(40)
        self.bookmarkNameLE.setObjectName("bookmarkNameLE")
        self.horizontalLayout_22.addWidget(self.bookmarkNameLE)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.okPb = PrimaryPushButton(web_inputBookmarkNameDialog)
        self.okPb.setObjectName("okPb")
        self.horizontalLayout_23.addWidget(self.okPb)
        self.cancelPb = PrimaryPushButton(web_inputBookmarkNameDialog)
        self.cancelPb.setObjectName("cancelPb")
        self.horizontalLayout_23.addWidget(self.cancelPb)
        self.verticalLayout.addLayout(self.horizontalLayout_23)

        self.retranslateUi(web_inputBookmarkNameDialog)
        QtCore.QMetaObject.connectSlotsByName(web_inputBookmarkNameDialog)

    def retranslateUi(self, web_inputBookmarkNameDialog):
        _translate = QtCore.QCoreApplication.translate
        web_inputBookmarkNameDialog.setWindowTitle(_translate("web_inputBookmarkNameDialog", "添加书签"))
        self.BodyLabel.setText(_translate("web_inputBookmarkNameDialog", "书签名:"))
        self.okPb.setText(_translate("web_inputBookmarkNameDialog", "确定(Space)"))
        self.okPb.setShortcut(_translate("web_inputBookmarkNameDialog", "Space"))
        self.cancelPb.setText(_translate("web_inputBookmarkNameDialog", "取消(Esc)"))
        self.cancelPb.setShortcut(_translate("web_inputBookmarkNameDialog", "Esc"))
from qfluentwidgets import BodyLabel, LineEdit, PrimaryPushButton
