# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\draw_dialog\web_selectProjectTypeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectWebProjectTypeDialog(object):
    def setupUi(self, selectWebProjectTypeDialog):
        selectWebProjectTypeDialog.setObjectName("selectWebProjectTypeDialog")
        selectWebProjectTypeDialog.resize(414, 124)
        self.verticalLayout = QtWidgets.QVBoxLayout(selectWebProjectTypeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.DrawRb = RadioButton(selectWebProjectTypeDialog)
        self.DrawRb.setChecked(True)
        self.DrawRb.setObjectName("DrawRb")
        self.buttonGroup = QtWidgets.QButtonGroup(selectWebProjectTypeDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.DrawRb)
        self.horizontalLayout_22.addWidget(self.DrawRb)
        self.ReviewRb = RadioButton(selectWebProjectTypeDialog)
        self.ReviewRb.setObjectName("ReviewRb")
        self.buttonGroup.addButton(self.ReviewRb)
        self.horizontalLayout_22.addWidget(self.ReviewRb)
        self.RandomRb = RadioButton(selectWebProjectTypeDialog)
        self.RandomRb.setObjectName("RandomRb")
        self.buttonGroup.addButton(self.RandomRb)
        self.horizontalLayout_22.addWidget(self.RandomRb)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.startPb = PrimaryPushButton(selectWebProjectTypeDialog)
        self.startPb.setObjectName("startPb")
        self.verticalLayout.addWidget(self.startPb)

        self.retranslateUi(selectWebProjectTypeDialog)
        QtCore.QMetaObject.connectSlotsByName(selectWebProjectTypeDialog)

    def retranslateUi(self, selectWebProjectTypeDialog):
        _translate = QtCore.QCoreApplication.translate
        selectWebProjectTypeDialog.setWindowTitle(_translate("selectWebProjectTypeDialog", "选择任务类型"))
        self.DrawRb.setText(_translate("selectWebProjectTypeDialog", "生产任务"))
        self.ReviewRb.setText(_translate("selectWebProjectTypeDialog", "质检任务"))
        self.RandomRb.setText(_translate("selectWebProjectTypeDialog", "抽检任务"))
        self.startPb.setText(_translate("selectWebProjectTypeDialog", "Open"))
from qfluentwidgets import PrimaryPushButton, RadioButton
