# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\tif_process_dialog\raster2shpDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_raster2VectorDialog(object):
    def setupUi(self, raster2VectorDialog):
        raster2VectorDialog.setObjectName("raster2VectorDialog")
        raster2VectorDialog.resize(557, 387)
        self.verticalLayout = QtWidgets.QVBoxLayout(raster2VectorDialog)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 7)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_4 = CardWidget(raster2VectorDialog)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel = BodyLabel(self.CardWidget_4)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_5.addWidget(self.BodyLabel)
        self.inputComboBox = ComboBox(self.CardWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputComboBox.sizePolicy().hasHeightForWidth())
        self.inputComboBox.setSizePolicy(sizePolicy)
        self.inputComboBox.setObjectName("inputComboBox")
        self.horizontalLayout_5.addWidget(self.inputComboBox)
        self.selectInputFilePB = ToolButton(self.CardWidget_4)
        self.selectInputFilePB.setObjectName("selectInputFilePB")
        self.horizontalLayout_5.addWidget(self.selectInputFilePB)
        self.verticalLayout.addWidget(self.CardWidget_4)
        self.CardWidget_2 = CardWidget(raster2VectorDialog)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CardWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        self.fieldNameLE = LineEdit(self.CardWidget_2)
        self.fieldNameLE.setObjectName("fieldNameLE")
        self.horizontalLayout_2.addWidget(self.fieldNameLE)
        self.verticalLayout.addWidget(self.CardWidget_2)
        self.CardWidget_3 = CardWidget(raster2VectorDialog)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.CardWidget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BodyLabel_3 = BodyLabel(self.CardWidget_3)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_4.addWidget(self.BodyLabel_3)
        self.postNameLE = LineEdit(self.CardWidget_3)
        self.postNameLE.setObjectName("postNameLE")
        self.horizontalLayout_4.addWidget(self.postNameLE)
        self.verticalLayout.addWidget(self.CardWidget_3)
        self.use8ConnectCB = CheckBox(raster2VectorDialog)
        self.use8ConnectCB.setObjectName("use8ConnectCB")
        self.verticalLayout.addWidget(self.use8ConnectCB)
        self.CardWidget = CardWidget(raster2VectorDialog)
        self.CardWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout.addWidget(self.BodyLabel_4)
        self.saveLE = LineEdit(self.CardWidget)
        self.saveLE.setObjectName("saveLE")
        self.horizontalLayout.addWidget(self.saveLE)
        self.selectSaveFilePB = ToolButton(self.CardWidget)
        self.selectSaveFilePB.setObjectName("selectSaveFilePB")
        self.horizontalLayout.addWidget(self.selectSaveFilePB)
        self.verticalLayout.addWidget(self.CardWidget)
        self.runPB = PushButton(raster2VectorDialog)
        self.runPB.setObjectName("runPB")
        self.verticalLayout.addWidget(self.runPB)

        self.retranslateUi(raster2VectorDialog)
        QtCore.QMetaObject.connectSlotsByName(raster2VectorDialog)

    def retranslateUi(self, raster2VectorDialog):
        _translate = QtCore.QCoreApplication.translate
        raster2VectorDialog.setWindowTitle(_translate("raster2VectorDialog", "Raster to Vector Parameter Settings"))
        self.BodyLabel.setText(_translate("raster2VectorDialog", "Select Raster or Folder"))
        self.BodyLabel_2.setText(_translate("raster2VectorDialog", "Input Shapefile Value Field"))
        self.BodyLabel_3.setText(_translate("raster2VectorDialog", "Input Result post"))
        self.use8ConnectCB.setText(_translate("raster2VectorDialog", "Use Eight-Directional Connectivity"))
        self.BodyLabel_4.setText(_translate("raster2VectorDialog", "Select Results Folder"))
        self.runPB.setText(_translate("raster2VectorDialog", "OK"))
from qfluentwidgets import BodyLabel, CardWidget, CheckBox, ComboBox, LineEdit, PushButton, ToolButton
