# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\tif_process_dialog\rasterExportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rasterExportDialog(object):
    def setupUi(self, rasterExportDialog):
        rasterExportDialog.setObjectName("rasterExportDialog")
        rasterExportDialog.resize(499, 202)
        self.verticalLayout = QtWidgets.QVBoxLayout(rasterExportDialog)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 7)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_4 = CardWidget(rasterExportDialog)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel = BodyLabel(self.CardWidget_4)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_5.addWidget(self.BodyLabel)
        self.selectTifCb = ComboBox(self.CardWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectTifCb.sizePolicy().hasHeightForWidth())
        self.selectTifCb.setSizePolicy(sizePolicy)
        self.selectTifCb.setObjectName("selectTifCb")
        self.horizontalLayout_5.addWidget(self.selectTifCb)
        self.verticalLayout.addWidget(self.CardWidget_4)
        self.CardWidget = CardWidget(rasterExportDialog)
        self.CardWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout.addWidget(self.BodyLabel_4)
        self.saveLE = LineEdit(self.CardWidget)
        self.saveLE.setReadOnly(True)
        self.saveLE.setObjectName("saveLE")
        self.horizontalLayout.addWidget(self.saveLE)
        self.selectSaveFilePB = ToolButton(self.CardWidget)
        self.selectSaveFilePB.setObjectName("selectSaveFilePB")
        self.horizontalLayout.addWidget(self.selectSaveFilePB)
        self.verticalLayout.addWidget(self.CardWidget)
        self.runPB = PushButton(rasterExportDialog)
        self.runPB.setObjectName("runPB")
        self.verticalLayout.addWidget(self.runPB)

        self.retranslateUi(rasterExportDialog)
        QtCore.QMetaObject.connectSlotsByName(rasterExportDialog)

    def retranslateUi(self, rasterExportDialog):
        _translate = QtCore.QCoreApplication.translate
        rasterExportDialog.setWindowTitle(_translate("rasterExportDialog", "Raster Export Parameter Settings"))
        self.BodyLabel.setText(_translate("rasterExportDialog", "Select Raster"))
        self.BodyLabel_4.setText(_translate("rasterExportDialog", "Result Path"))
        self.runPB.setText(_translate("rasterExportDialog", "OK"))
from qfluentwidgets import BodyLabel, CardWidget, ComboBox, LineEdit, PushButton, ToolButton
