# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\tif_process_dialog\rasterBuildOverviewDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_buildOverviewDialog(object):
    def setupUi(self, buildOverviewDialog):
        buildOverviewDialog.setObjectName("buildOverviewDialog")
        buildOverviewDialog.resize(371, 170)
        self.verticalLayout = QtWidgets.QVBoxLayout(buildOverviewDialog)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 7)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_4 = CardWidget(buildOverviewDialog)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel = BodyLabel(self.CardWidget_4)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_5.addWidget(self.BodyLabel)
        self.selectTifCb = ComboBox(self.CardWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectTifCb.sizePolicy().hasHeightForWidth())
        self.selectTifCb.setSizePolicy(sizePolicy)
        self.selectTifCb.setObjectName("selectTifCb")
        self.horizontalLayout_5.addWidget(self.selectTifCb)
        self.verticalLayout.addWidget(self.CardWidget_4)
        self.buildInMyselfCb = CheckBox(buildOverviewDialog)
        self.buildInMyselfCb.setObjectName("buildInMyselfCb")
        self.verticalLayout.addWidget(self.buildInMyselfCb)
        self.cleanCb = CheckBox(buildOverviewDialog)
        self.cleanCb.setObjectName("cleanCb")
        self.verticalLayout.addWidget(self.cleanCb)
        self.runPB = PushButton(buildOverviewDialog)
        self.runPB.setObjectName("runPB")
        self.verticalLayout.addWidget(self.runPB)

        self.retranslateUi(buildOverviewDialog)
        QtCore.QMetaObject.connectSlotsByName(buildOverviewDialog)

    def retranslateUi(self, buildOverviewDialog):
        _translate = QtCore.QCoreApplication.translate
        buildOverviewDialog.setWindowTitle(_translate("buildOverviewDialog", "Raster Build Overview Parameter Settings"))
        self.BodyLabel.setText(_translate("buildOverviewDialog", "Select Raster"))
        self.buildInMyselfCb.setText(_translate("buildOverviewDialog", "Build inner"))
        self.cleanCb.setText(_translate("buildOverviewDialog", "Delete if exist"))
        self.runPB.setText(_translate("buildOverviewDialog", "OK"))
from qfluentwidgets import BodyLabel, CardWidget, CheckBox, ComboBox, PushButton
