# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\tif_process_dialog\rasterZonalStaticDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rasterZonalStaticDialog(object):
    def setupUi(self, rasterZonalStaticDialog):
        rasterZonalStaticDialog.setObjectName("rasterZonalStaticDialog")
        rasterZonalStaticDialog.resize(494, 316)
        self.verticalLayout = QtWidgets.QVBoxLayout(rasterZonalStaticDialog)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 7)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_4 = CardWidget(rasterZonalStaticDialog)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel = BodyLabel(self.CardWidget_4)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_5.addWidget(self.BodyLabel)
        self.inputLE = LineEdit(self.CardWidget_4)
        self.inputLE.setObjectName("inputLE")
        self.horizontalLayout_5.addWidget(self.inputLE)
        self.selectInputFilePB = ToolButton(self.CardWidget_4)
        self.selectInputFilePB.setObjectName("selectInputFilePB")
        self.horizontalLayout_5.addWidget(self.selectInputFilePB)
        self.verticalLayout.addWidget(self.CardWidget_4)
        self.CardWidget_6 = CardWidget(rasterZonalStaticDialog)
        self.CardWidget_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_6.setObjectName("CardWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.CardWidget_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.BodyLabel_2 = BodyLabel(self.CardWidget_6)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_7.addWidget(self.BodyLabel_2)
        self.inputShpLE = LineEdit(self.CardWidget_6)
        self.inputShpLE.setObjectName("inputShpLE")
        self.horizontalLayout_7.addWidget(self.inputShpLE)
        self.selectInputShpPB = ToolButton(self.CardWidget_6)
        self.selectInputShpPB.setObjectName("selectInputShpPB")
        self.horizontalLayout_7.addWidget(self.selectInputShpPB)
        self.verticalLayout.addWidget(self.CardWidget_6)
        self.CardWidget = CardWidget(rasterZonalStaticDialog)
        self.CardWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout.addWidget(self.BodyLabel_4)
        self.saveLE = LineEdit(self.CardWidget)
        self.saveLE.setObjectName("saveLE")
        self.horizontalLayout.addWidget(self.saveLE)
        self.selectSaveFilePB = ToolButton(self.CardWidget)
        self.selectSaveFilePB.setObjectName("selectSaveFilePB")
        self.horizontalLayout.addWidget(self.selectSaveFilePB)
        self.verticalLayout.addWidget(self.CardWidget)
        self.runPB = PushButton(rasterZonalStaticDialog)
        self.runPB.setObjectName("runPB")
        self.verticalLayout.addWidget(self.runPB)

        self.retranslateUi(rasterZonalStaticDialog)
        QtCore.QMetaObject.connectSlotsByName(rasterZonalStaticDialog)

    def retranslateUi(self, rasterZonalStaticDialog):
        _translate = QtCore.QCoreApplication.translate
        rasterZonalStaticDialog.setWindowTitle(_translate("rasterZonalStaticDialog", "Raster Zonal Static Parameter Settings"))
        self.BodyLabel.setText(_translate("rasterZonalStaticDialog", "Select Raster"))
        self.BodyLabel_2.setText(_translate("rasterZonalStaticDialog", "Select Vector"))
        self.BodyLabel_4.setText(_translate("rasterZonalStaticDialog", "Result Path"))
        self.runPB.setText(_translate("rasterZonalStaticDialog", "OK"))
from qfluentwidgets import BodyLabel, CardWidget, LineEdit, PushButton, ToolButton
