# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\tif_process_dialog\rasterRecombineDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rasterRecombineDialog(object):
    def setupUi(self, rasterRecombineDialog):
        rasterRecombineDialog.setObjectName("rasterRecombineDialog")
        rasterRecombineDialog.resize(499, 271)
        self.verticalLayout = QtWidgets.QVBoxLayout(rasterRecombineDialog)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 7)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_4 = CardWidget(rasterRecombineDialog)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel = BodyLabel(self.CardWidget_4)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_5.addWidget(self.BodyLabel)
        self.selectTifCb = ComboBox(self.CardWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectTifCb.sizePolicy().hasHeightForWidth())
        self.selectTifCb.setSizePolicy(sizePolicy)
        self.selectTifCb.setObjectName("selectTifCb")
        self.horizontalLayout_5.addWidget(self.selectTifCb)
        self.verticalLayout.addWidget(self.CardWidget_4)
        self.BodyLabel_3 = BodyLabel(rasterRecombineDialog)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.verticalLayout.addWidget(self.BodyLabel_3)
        self.CardWidget_2 = CardWidget(rasterRecombineDialog)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CardWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        self.recombineLE = LineEdit(self.CardWidget_2)
        self.recombineLE.setObjectName("recombineLE")
        self.horizontalLayout_2.addWidget(self.recombineLE)
        self.verticalLayout.addWidget(self.CardWidget_2)
        self.CardWidget = CardWidget(rasterRecombineDialog)
        self.CardWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout.addWidget(self.BodyLabel_4)
        self.saveLE = LineEdit(self.CardWidget)
        self.saveLE.setReadOnly(True)
        self.saveLE.setObjectName("saveLE")
        self.horizontalLayout.addWidget(self.saveLE)
        self.selectSaveFilePB = ToolButton(self.CardWidget)
        self.selectSaveFilePB.setObjectName("selectSaveFilePB")
        self.horizontalLayout.addWidget(self.selectSaveFilePB)
        self.verticalLayout.addWidget(self.CardWidget)
        self.runPB = PushButton(rasterRecombineDialog)
        self.runPB.setObjectName("runPB")
        self.verticalLayout.addWidget(self.runPB)

        self.retranslateUi(rasterRecombineDialog)
        QtCore.QMetaObject.connectSlotsByName(rasterRecombineDialog)

    def retranslateUi(self, rasterRecombineDialog):
        _translate = QtCore.QCoreApplication.translate
        rasterRecombineDialog.setWindowTitle(_translate("rasterRecombineDialog", "Raster Recombine Parameter Settings"))
        self.BodyLabel.setText(_translate("rasterRecombineDialog", "Select Raster"))
        self.BodyLabel_3.setText(_translate("rasterRecombineDialog", "Recombine Order Indication: 3, 2, 1"))
        self.BodyLabel_2.setText(_translate("rasterRecombineDialog", "Recombine Order"))
        self.BodyLabel_4.setText(_translate("rasterRecombineDialog", "Result Path"))
        self.runPB.setText(_translate("rasterRecombineDialog", "OK"))
from qfluentwidgets import BodyLabel, CardWidget, ComboBox, LineEdit, PushButton, ToolButton
