import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

from .draw_dialog_attrEditDialog import AttrEditDialog

from .fluentDiyWidgets import YoyiStateToolTip
from .layerPropWindowWidget import LayerPropWindowWidgeter

from .commonTool_openXYZTilesDialog import OpenXYZTilesDialogClass
from .commonTool_jl1FreeXYZTilesDialog import JL1FreeXYZTilesDialogClass
from .commonTool_createFishNetDialog import CreateFishNetDialogClass
from .commonTool_shpCommonProcessDialog import ShpCommonProcessDialogClass

from .tifProcess_raster2shpDialog import Raster2ShpDialog
from .tifProcess_tifRecombineDialog import TifRecombineDialog
from .tifProcess_tifExportDialog import TifExportDialog
from .tifProcess_raster16to8Dialog import Raster16to8Dialog
from .tifProcess_tifBuildOverviewDialog import TifBuildOverviewDialog
from .tifProcess_rasterClipDialog import RasterClipDialogClass
from .tifProcess_rasterReprojectDialog import RasterReprojectDialogClass
from .tifProcess_rasterMergeDialog import RasterMergeDialogClass
from .tifProcess_rasterCalcDialog import RasterCalcDialogClass
from .tifProcess_rasterZonalStaticDialog import RasterZonalStaticDialog

from .shpProcess_shp2rasterDialog import Shp2RasterDialogClass
from .shpProcess_shpExportDialog import ShpExportDialogClass
from .shpProcess_shpFixGeometryDialog import ShpFixGeometryDialogClass
from .shpProcess_shpClipDialog import ShpClipDialogClass
from .shpProcess_shpEraseDialog import ShpEraseDialogClass
from .shpProcess_shpSimplyDialog import ShpSimplyDialogClass
from .shpProcess_shpBufferDialog import ShpBufferDialogClass
from .shpProcess_shpIntersectionDialog import ShpIntersectionDialogClass
from .shpProcess_shpOrthogoDialog import ShpOrthogoDialogClass
from .shpProcess_shpCalCentroidDialog import ShpCalCentroidDialogClass
from .shpProcess_shpCalAreaDialog import ShpCalAreaDialogClass
from .shpProcess_shpDissolveDialog import ShpDissolveDialogClass
from .shpProcess_shpSinglepartsDialog import ShpSinglepartsDialogClass
from .shpProcess_shpSmoothDialog import ShpSmoothDialogClass
from .shpProcess_shpMergeDialog import ShpMergeDialogClass
from .shpProcess_shpReprojectDialog import ShpReprojectDialogClass
from .shpProcess_shpRemoveAreaDialog import ShpRemoveAreaDialogClass
from .shpProcess_shpDeleteholesDialog import ShpDeleteholesDialogClass
from .shpProcess_shpChangeAnalysisDialog import ShpChangeAnalysisDialogClass

try:
    from .shpProcess_excelExportDialog import ExcelExportDialogClass
    from .shpProcess_excelTransLineDialog import ExcelTransLineDialogClass
except Exception as e:
    pass

from .infer_dialog_generateDatasetDialog import GenerateDatasetDialogClass
from .infer_dialog_splitDatasetDialog import SplitDatasetDialogClass

try:
    from .infer_dialog_seg import InferSegDialog
    from .infer_dialog_detection import InferDetecDialog
    from .infer_dialog_changeDetec import InferChangeDetecDialog
    from .infer_dialog_batchInferDialog import BatchInferDialog
    from .infer_dialog_customSeg import InferCustomSegDialog
    from .infer_dialog_openTrainToolDialog import OpenTrainToolDialogClass
    from .infer_dialog_trainDialog import TrainDialogClass
except Exception as e:
    pass