# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(596, 491)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SubtitleLabel = SubtitleLabel(Frame)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.horizontalLayout_2.addWidget(self.SubtitleLabel)
        self.userLabel = BodyLabel(Frame)
        self.userLabel.setObjectName("userLabel")
        self.horizontalLayout_2.addWidget(self.userLabel)
        self.changeLoginStatePb = PushButton(Frame)
        self.changeLoginStatePb.setObjectName("changeLoginStatePb")
        self.horizontalLayout_2.addWidget(self.changeLoginStatePb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.SubtitleLabel_2 = SubtitleLabel(Frame)
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.horizontalLayout_10.addWidget(self.SubtitleLabel_2)
        self.refreshPb = ToolButton(Frame)
        self.refreshPb.setObjectName("refreshPb")
        self.horizontalLayout_10.addWidget(self.refreshPb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.pkgTableWidget = TableWidget(Frame)
        self.pkgTableWidget.setObjectName("pkgTableWidget")
        self.pkgTableWidget.setColumnCount(0)
        self.pkgTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.pkgTableWidget)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.SubtitleLabel_3 = SubtitleLabel(Frame)
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.horizontalLayout_11.addWidget(self.SubtitleLabel_3)
        self.saveDirLE = LineEdit(Frame)
        self.saveDirLE.setObjectName("saveDirLE")
        self.horizontalLayout_11.addWidget(self.saveDirLE)
        self.selectSaveDirPb = PushButton(Frame)
        self.selectSaveDirPb.setObjectName("selectSaveDirPb")
        self.horizontalLayout_11.addWidget(self.selectSaveDirPb)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.downloadPb = PushButton(Frame)
        self.downloadPb.setObjectName("downloadPb")
        self.horizontalLayout_12.addWidget(self.downloadPb)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.progressBar = ProgressBar(Frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.SubtitleLabel.setText(_translate("Frame", "登录人员："))
        self.userLabel.setText(_translate("Frame", "Unknown"))
        self.changeLoginStatePb.setText(_translate("Frame", "登录"))
        self.SubtitleLabel_2.setText(_translate("Frame", "选择任务包"))
        self.SubtitleLabel_3.setText(_translate("Frame", "下载地址："))
        self.selectSaveDirPb.setText(_translate("Frame", "..."))
        self.downloadPb.setText(_translate("Frame", "开始下载"))
from qfluentwidgets import BodyLabel, LineEdit, ProgressBar, PushButton, SubtitleLabel, TableWidget, ToolButton
