# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\jointWorkWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YoyiJointWorkWindow(object):
    def setupUi(self, YoyiJointWorkWindow):
        YoyiJointWorkWindow.setObjectName("YoyiJointWorkWindow")
        YoyiJointWorkWindow.resize(1457, 713)
        YoyiJointWorkWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(YoyiJointWorkWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftFrame = QtWidgets.QFrame(self.splitter)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.rightFrame = QtWidgets.QFrame(self.splitter)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.horizontalLayout_8.addWidget(self.splitter)
        self.horizontalLayout.addWidget(self.frame)
        YoyiJointWorkWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(YoyiJointWorkWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.openProjectPb = PushButton(self.dockWidgetContents)
        self.openProjectPb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.openProjectPb.setObjectName("openProjectPb")
        self.horizontalLayout_5.addWidget(self.openProjectPb)
        self.closeProjectPb = PushButton(self.dockWidgetContents)
        self.closeProjectPb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.closeProjectPb.setObjectName("closeProjectPb")
        self.horizontalLayout_5.addWidget(self.closeProjectPb)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.BodyLabel = BodyLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel.sizePolicy().hasHeightForWidth())
        self.BodyLabel.setSizePolicy(sizePolicy)
        self.BodyLabel.setProperty("pixelFontSize", 11)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_10.addWidget(self.BodyLabel)
        self.projectLabel = BodyLabel(self.dockWidgetContents)
        self.projectLabel.setWordWrap(True)
        self.projectLabel.setProperty("pixelFontSize", 12)
        self.projectLabel.setObjectName("projectLabel")
        self.horizontalLayout_10.addWidget(self.projectLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_3 = BodyLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_3.sizePolicy().hasHeightForWidth())
        self.BodyLabel_3.setSizePolicy(sizePolicy)
        self.BodyLabel_3.setProperty("pixelFontSize", 11)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_2.addWidget(self.BodyLabel_3)
        self.errorReasonLabel = BodyLabel(self.dockWidgetContents)
        self.errorReasonLabel.setWordWrap(True)
        self.errorReasonLabel.setProperty("pixelFontSize", 12)
        self.errorReasonLabel.setObjectName("errorReasonLabel")
        self.horizontalLayout_2.addWidget(self.errorReasonLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.BodyLabel_5 = BodyLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_5.sizePolicy().hasHeightForWidth())
        self.BodyLabel_5.setSizePolicy(sizePolicy)
        self.BodyLabel_5.setProperty("pixelFontSize", 11)
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.horizontalLayout_9.addWidget(self.BodyLabel_5)
        self.randomRejectReasonLabel = BodyLabel(self.dockWidgetContents)
        self.randomRejectReasonLabel.setWordWrap(True)
        self.randomRejectReasonLabel.setProperty("pixelFontSize", 12)
        self.randomRejectReasonLabel.setObjectName("randomRejectReasonLabel")
        self.horizontalLayout_9.addWidget(self.randomRejectReasonLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.isOpenAttrWindowSB = SwitchButton(self.dockWidgetContents)
        self.isOpenAttrWindowSB.setChecked(True)
        self.isOpenAttrWindowSB.setObjectName("isOpenAttrWindowSB")
        self.verticalLayout.addWidget(self.isOpenAttrWindowSB)
        self.hl_qwer = QtWidgets.QHBoxLayout()
        self.hl_qwer.setSpacing(1)
        self.hl_qwer.setObjectName("hl_qwer")
        self.verticalLayout.addLayout(self.hl_qwer)
        self.hl_asdf = QtWidgets.QHBoxLayout()
        self.hl_asdf.setSpacing(1)
        self.hl_asdf.setObjectName("hl_asdf")
        self.verticalLayout.addLayout(self.hl_asdf)
        self.hl_zxcv = QtWidgets.QHBoxLayout()
        self.hl_zxcv.setSpacing(1)
        self.hl_zxcv.setObjectName("hl_zxcv")
        self.verticalLayout.addLayout(self.hl_zxcv)
        self.hl_f1234 = QtWidgets.QHBoxLayout()
        self.hl_f1234.setSpacing(1)
        self.hl_f1234.setObjectName("hl_f1234")
        self.verticalLayout.addLayout(self.hl_f1234)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fishnetsTotalLabel = StrongBodyLabel(self.dockWidgetContents)
        self.fishnetsTotalLabel.setWordWrap(True)
        self.fishnetsTotalLabel.setProperty("pixelFontSize", 11)
        self.fishnetsTotalLabel.setObjectName("fishnetsTotalLabel")
        self.gridLayout_2.addWidget(self.fishnetsTotalLabel, 0, 0, 1, 1)
        self.pageSizeComboBox = ComboBox(self.dockWidgetContents)
        self.pageSizeComboBox.setObjectName("pageSizeComboBox")
        self.gridLayout_2.addWidget(self.pageSizeComboBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.statusFilterCb = ComboBox(self.dockWidgetContents)
        self.statusFilterCb.setMinimumSize(QtCore.QSize(0, 0))
        self.statusFilterCb.setObjectName("statusFilterCb")
        self.gridLayout_3.addWidget(self.statusFilterCb, 0, 1, 1, 1)
        self.BodyLabel_2 = BodyLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_2.sizePolicy().hasHeightForWidth())
        self.BodyLabel_2.setSizePolicy(sizePolicy)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout_3.addWidget(self.BodyLabel_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.TableWidget = TableWidget(self.dockWidgetContents)
        self.TableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.TableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lastPagePb = PrimaryPushButton(self.dockWidgetContents)
        self.lastPagePb.setObjectName("lastPagePb")
        self.horizontalLayout_3.addWidget(self.lastPagePb)
        self.nextPagePb = PrimaryPushButton(self.dockWidgetContents)
        self.nextPagePb.setObjectName("nextPagePb")
        self.horizontalLayout_3.addWidget(self.nextPagePb)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pageIndexSpinBox = SpinBox(self.dockWidgetContents)
        self.pageIndexSpinBox.setMaximumSize(QtCore.QSize(16777215, 33))
        self.pageIndexSpinBox.setStyleSheet("SpinBox, DoubleSpinBox, DateEdit, DateTimeEdit, TimeEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 20px 0 5px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"SpinBox:hover,\n"
"DoubleSpinBox:hover,\n"
"DateEdit:hover,\n"
"DateTimeEdit:hover,\n"
"TimeEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"SpinBox:focus,\n"
"DoubleSpinBox:focus,\n"
"DateEdit:focus,\n"
"DateTimeEdit:focus,\n"
"TimeEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"SpinBox:disabled,\n"
"DoubleSpinBox:disabled,\n"
"DateEdit:disabled,\n"
"DateTimeEdit:disabled,\n"
"TimeEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"SpinButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"SpinButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"SpinButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.pageIndexSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pageIndexSpinBox.setMaximum(999999)
        self.pageIndexSpinBox.setObjectName("pageIndexSpinBox")
        self.horizontalLayout_4.addWidget(self.pageIndexSpinBox)
        self.BodyLabel_7 = BodyLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_7.sizePolicy().hasHeightForWidth())
        self.BodyLabel_7.setSizePolicy(sizePolicy)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.horizontalLayout_4.addWidget(self.BodyLabel_7)
        self.jumpPb = PrimaryPushButton(self.dockWidgetContents)
        self.jumpPb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.jumpPb.setObjectName("jumpPb")
        self.horizontalLayout_4.addWidget(self.jumpPb)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.dockWidget.setWidget(self.dockWidgetContents)
        YoyiJointWorkWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.dockWidgetTop = QtWidgets.QDockWidget(YoyiJointWorkWindow)
        self.dockWidgetTop.setStyleSheet("")
        self.dockWidgetTop.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetTop.setObjectName("dockWidgetTop")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.addRasterLayer = PushButton(self.dockWidgetContents_2)
        self.addRasterLayer.setObjectName("addRasterLayer")
        self.horizontalLayout_16.addWidget(self.addRasterLayer)
        self.addVectorLayer = PushButton(self.dockWidgetContents_2)
        self.addVectorLayer.setObjectName("addVectorLayer")
        self.horizontalLayout_16.addWidget(self.addVectorLayer)
        self.addXYZTilesLayer = PushButton(self.dockWidgetContents_2)
        self.addXYZTilesLayer.setObjectName("addXYZTilesLayer")
        self.horizontalLayout_16.addWidget(self.addXYZTilesLayer)
        self.line = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_16.addWidget(self.line)
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_16.addWidget(self.line_2)
        self.BodyLabel_6 = BodyLabel(self.dockWidgetContents_2)
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.horizontalLayout_16.addWidget(self.BodyLabel_6)
        self.leftChangePb1 = PillToolButton(self.dockWidgetContents_2)
        self.leftChangePb1.setObjectName("leftChangePb1")
        self.horizontalLayout_16.addWidget(self.leftChangePb1)
        self.leftChangePb2 = PillToolButton(self.dockWidgetContents_2)
        self.leftChangePb2.setObjectName("leftChangePb2")
        self.horizontalLayout_16.addWidget(self.leftChangePb2)
        self.line_3 = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_16.addWidget(self.line_3)
        self.line_4 = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_16.addWidget(self.line_4)
        self.BodyLabel_9 = BodyLabel(self.dockWidgetContents_2)
        self.BodyLabel_9.setObjectName("BodyLabel_9")
        self.horizontalLayout_16.addWidget(self.BodyLabel_9)
        self.rightChangePb3 = PillToolButton(self.dockWidgetContents_2)
        self.rightChangePb3.setObjectName("rightChangePb3")
        self.horizontalLayout_16.addWidget(self.rightChangePb3)
        self.rightChangePb4 = PillToolButton(self.dockWidgetContents_2)
        self.rightChangePb4.setObjectName("rightChangePb4")
        self.horizontalLayout_16.addWidget(self.rightChangePb4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.selectFishnetMapToolPb = PillPushButton(self.dockWidgetContents_2)
        self.selectFishnetMapToolPb.setObjectName("selectFishnetMapToolPb")
        self.horizontalLayout_16.addWidget(self.selectFishnetMapToolPb)
        self.leftBottomInfoPb = PrimaryPushButton(self.dockWidgetContents_2)
        self.leftBottomInfoPb.setObjectName("leftBottomInfoPb")
        self.horizontalLayout_16.addWidget(self.leftBottomInfoPb)
        self.rightBottomInfoPb = PrimaryPushButton(self.dockWidgetContents_2)
        self.rightBottomInfoPb.setObjectName("rightBottomInfoPb")
        self.horizontalLayout_16.addWidget(self.rightBottomInfoPb)
        self.deleteFeaturePb = PillToolButton(self.dockWidgetContents_2)
        self.deleteFeaturePb.setMaximumSize(QtCore.QSize(40, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resources/gis/shp_delete_select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteFeaturePb.setIcon(icon)
        self.deleteFeaturePb.setIconSize(QtCore.QSize(30, 30))
        self.deleteFeaturePb.setCheckable(False)
        self.deleteFeaturePb.setObjectName("deleteFeaturePb")
        self.horizontalLayout_16.addWidget(self.deleteFeaturePb)
        self.rejectPointMapToolPb = PillToolButton(self.dockWidgetContents_2)
        self.rejectPointMapToolPb.setMaximumSize(QtCore.QSize(40, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/resources/other_loadPCC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rejectPointMapToolPb.setIcon(icon1)
        self.rejectPointMapToolPb.setIconSize(QtCore.QSize(30, 30))
        self.rejectPointMapToolPb.setCheckable(True)
        self.rejectPointMapToolPb.setObjectName("rejectPointMapToolPb")
        self.horizontalLayout_16.addWidget(self.rejectPointMapToolPb)
        self.commitMagicPB = PillToolButton(self.dockWidgetContents_2)
        self.commitMagicPB.setMaximumSize(QtCore.QSize(40, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/resources/shpProcess/commonProcess.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commitMagicPB.setIcon(icon2)
        self.commitMagicPB.setIconSize(QtCore.QSize(30, 30))
        self.commitMagicPB.setCheckable(False)
        self.commitMagicPB.setObjectName("commitMagicPB")
        self.horizontalLayout_16.addWidget(self.commitMagicPB)
        self.addBookmarkPb = PrimarySplitPushButton(self.dockWidgetContents_2)
        self.addBookmarkPb.setObjectName("addBookmarkPb")
        self.horizontalLayout_16.addWidget(self.addBookmarkPb)
        self.deleteBookmarkPb = PrimarySplitPushButton(self.dockWidgetContents_2)
        self.deleteBookmarkPb.setObjectName("deleteBookmarkPb")
        self.horizontalLayout_16.addWidget(self.deleteBookmarkPb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.dockWidgetTop.setWidget(self.dockWidgetContents_2)
        YoyiJointWorkWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetTop)
        self.dockWidget_left = QtWidgets.QDockWidget(YoyiJointWorkWindow)
        self.dockWidget_left.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_left.setObjectName("dockWidget_left")
        self.dockWidgetContentsLeft = QtWidgets.QWidget()
        self.dockWidgetContentsLeft.setObjectName("dockWidgetContentsLeft")
        self.dockWidget_left.setWidget(self.dockWidgetContentsLeft)
        YoyiJointWorkWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_left)
        self.dockWidget_leftDown = QtWidgets.QDockWidget(YoyiJointWorkWindow)
        self.dockWidget_leftDown.setStyleSheet("")
        self.dockWidget_leftDown.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_leftDown.setObjectName("dockWidget_leftDown")
        self.dockWidgetContentsLeftDown = QtWidgets.QWidget()
        self.dockWidgetContentsLeftDown.setObjectName("dockWidgetContentsLeftDown")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContentsLeftDown)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.featureTotalLabel = StrongBodyLabel(self.dockWidgetContentsLeftDown)
        self.featureTotalLabel.setWordWrap(True)
        self.featureTotalLabel.setProperty("pixelFontSize", 11)
        self.featureTotalLabel.setObjectName("featureTotalLabel")
        self.gridLayout_4.addWidget(self.featureTotalLabel, 0, 0, 1, 1)
        self.featurePageSizeComboBox = ComboBox(self.dockWidgetContentsLeftDown)
        self.featurePageSizeComboBox.setObjectName("featurePageSizeComboBox")
        self.gridLayout_4.addWidget(self.featurePageSizeComboBox, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.BodyLabel_4 = BodyLabel(self.dockWidgetContentsLeftDown)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_4.sizePolicy().hasHeightForWidth())
        self.BodyLabel_4.setSizePolicy(sizePolicy)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout_5.addWidget(self.BodyLabel_4, 0, 0, 1, 1)
        self.featureStatusFilterCb = ComboBox(self.dockWidgetContentsLeftDown)
        self.featureStatusFilterCb.setMinimumSize(QtCore.QSize(0, 0))
        self.featureStatusFilterCb.setObjectName("featureStatusFilterCb")
        self.gridLayout_5.addWidget(self.featureStatusFilterCb, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_5)
        self.featureTableWidget = TableWidget(self.dockWidgetContentsLeftDown)
        self.featureTableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.featureTableWidget.setObjectName("featureTableWidget")
        self.featureTableWidget.setColumnCount(0)
        self.featureTableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.featureTableWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lastFeaturePagePb = PrimaryPushButton(self.dockWidgetContentsLeftDown)
        self.lastFeaturePagePb.setObjectName("lastFeaturePagePb")
        self.horizontalLayout_6.addWidget(self.lastFeaturePagePb)
        self.nextFeaturePagePb = PrimaryPushButton(self.dockWidgetContentsLeftDown)
        self.nextFeaturePagePb.setObjectName("nextFeaturePagePb")
        self.horizontalLayout_6.addWidget(self.nextFeaturePagePb)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.featurePageIndexSpinBox = SpinBox(self.dockWidgetContentsLeftDown)
        self.featurePageIndexSpinBox.setMaximumSize(QtCore.QSize(999999, 33))
        self.featurePageIndexSpinBox.setStyleSheet("SpinBox, DoubleSpinBox, DateEdit, DateTimeEdit, TimeEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 30px 0 5px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"SpinBox:hover,\n"
"DoubleSpinBox:hover,\n"
"DateEdit:hover,\n"
"DateTimeEdit:hover,\n"
"TimeEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"SpinBox:focus,\n"
"DoubleSpinBox:focus,\n"
"DateEdit:focus,\n"
"DateTimeEdit:focus,\n"
"TimeEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"SpinBox:disabled,\n"
"DoubleSpinBox:disabled,\n"
"DateEdit:disabled,\n"
"DateTimeEdit:disabled,\n"
"TimeEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"SpinButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"SpinButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"SpinButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}")
        self.featurePageIndexSpinBox.setMaximum(999999)
        self.featurePageIndexSpinBox.setObjectName("featurePageIndexSpinBox")
        self.horizontalLayout_7.addWidget(self.featurePageIndexSpinBox)
        self.BodyLabel_8 = BodyLabel(self.dockWidgetContentsLeftDown)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_8.sizePolicy().hasHeightForWidth())
        self.BodyLabel_8.setSizePolicy(sizePolicy)
        self.BodyLabel_8.setObjectName("BodyLabel_8")
        self.horizontalLayout_7.addWidget(self.BodyLabel_8)
        self.featureJumpPb = PrimaryPushButton(self.dockWidgetContentsLeftDown)
        self.featureJumpPb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.featureJumpPb.setObjectName("featureJumpPb")
        self.horizontalLayout_7.addWidget(self.featureJumpPb)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.dockWidget_leftDown.setWidget(self.dockWidgetContentsLeftDown)
        YoyiJointWorkWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_leftDown)

        self.retranslateUi(YoyiJointWorkWindow)
        QtCore.QMetaObject.connectSlotsByName(YoyiJointWorkWindow)

    def retranslateUi(self, YoyiJointWorkWindow):
        _translate = QtCore.QCoreApplication.translate
        self.dockWidget.setWindowTitle(_translate("YoyiJointWorkWindow", "右侧工具栏"))
        self.openProjectPb.setText(_translate("YoyiJointWorkWindow", "打开项目"))
        self.closeProjectPb.setText(_translate("YoyiJointWorkWindow", "关闭项目"))
        self.BodyLabel.setText(_translate("YoyiJointWorkWindow", "当前项目："))
        self.projectLabel.setText(_translate("YoyiJointWorkWindow", "Unknown"))
        self.BodyLabel_3.setText(_translate("YoyiJointWorkWindow", "质检驳回原因："))
        self.errorReasonLabel.setText(_translate("YoyiJointWorkWindow", "Unknown"))
        self.BodyLabel_5.setText(_translate("YoyiJointWorkWindow", "抽检驳回原因："))
        self.randomRejectReasonLabel.setText(_translate("YoyiJointWorkWindow", "Unknown"))
        self.isOpenAttrWindowSB.setText(_translate("YoyiJointWorkWindow", "勾画后填写属性"))
        self.isOpenAttrWindowSB.setOnText(_translate("YoyiJointWorkWindow", "勾画后填写属性"))
        self.isOpenAttrWindowSB.setOffText(_translate("YoyiJointWorkWindow", "勾画后属性置空"))
        self.fishnetsTotalLabel.setText(_translate("YoyiJointWorkWindow", "1-10 共100个格网"))
        self.BodyLabel_2.setText(_translate("YoyiJointWorkWindow", "格网状态"))
        self.lastPagePb.setText(_translate("YoyiJointWorkWindow", "上一页"))
        self.nextPagePb.setText(_translate("YoyiJointWorkWindow", "下一页"))
        self.BodyLabel_7.setText(_translate("YoyiJointWorkWindow", "页"))
        self.jumpPb.setText(_translate("YoyiJointWorkWindow", "跳转"))
        self.dockWidgetTop.setWindowTitle(_translate("YoyiJointWorkWindow", "顶部工具栏"))
        self.addRasterLayer.setText(_translate("YoyiJointWorkWindow", "添加本地影像"))
        self.addVectorLayer.setText(_translate("YoyiJointWorkWindow", "添加本地矢量"))
        self.addXYZTilesLayer.setText(_translate("YoyiJointWorkWindow", "添加xyzTiles"))
        self.BodyLabel_6.setText(_translate("YoyiJointWorkWindow", "左侧底图变更"))
        self.leftChangePb1.setText(_translate("YoyiJointWorkWindow", "1"))
        self.leftChangePb1.setShortcut(_translate("YoyiJointWorkWindow", "1"))
        self.leftChangePb2.setText(_translate("YoyiJointWorkWindow", "2"))
        self.leftChangePb2.setShortcut(_translate("YoyiJointWorkWindow", "2"))
        self.BodyLabel_9.setText(_translate("YoyiJointWorkWindow", "右侧底图变更"))
        self.rightChangePb3.setText(_translate("YoyiJointWorkWindow", "3"))
        self.rightChangePb3.setShortcut(_translate("YoyiJointWorkWindow", "3"))
        self.rightChangePb4.setText(_translate("YoyiJointWorkWindow", "4"))
        self.rightChangePb4.setShortcut(_translate("YoyiJointWorkWindow", "4"))
        self.selectFishnetMapToolPb.setText(_translate("YoyiJointWorkWindow", "格网选择工具"))
        self.leftBottomInfoPb.setText(_translate("YoyiJointWorkWindow", "左侧底图信息"))
        self.rightBottomInfoPb.setText(_translate("YoyiJointWorkWindow", "右侧底图信息"))
        self.deleteFeaturePb.setToolTip(_translate("YoyiJointWorkWindow", "Delete Feature Tool (Del)"))
        self.deleteFeaturePb.setShortcut(_translate("YoyiJointWorkWindow", "Del"))
        self.rejectPointMapToolPb.setToolTip(_translate("YoyiJointWorkWindow", "错误点位标记(~)"))
        self.rejectPointMapToolPb.setShortcut(_translate("YoyiJointWorkWindow", "`"))
        self.commitMagicPB.setToolTip(_translate("YoyiJointWorkWindow", "提交Magic"))
        self.commitMagicPB.setShortcut(_translate("YoyiJointWorkWindow", "Space"))
        self.addBookmarkPb.setProperty("text_", _translate("YoyiJointWorkWindow", "添加书签"))
        self.deleteBookmarkPb.setProperty("text_", _translate("YoyiJointWorkWindow", "清空书签"))
        self.dockWidget_left.setWindowTitle(_translate("YoyiJointWorkWindow", "图层树"))
        self.dockWidget_leftDown.setWindowTitle(_translate("YoyiJointWorkWindow", "要素属性表"))
        self.featureTotalLabel.setText(_translate("YoyiJointWorkWindow", "1-10 共100个要素"))
        self.BodyLabel_4.setText(_translate("YoyiJointWorkWindow", "要素排序"))
        self.lastFeaturePagePb.setText(_translate("YoyiJointWorkWindow", "上一页"))
        self.nextFeaturePagePb.setText(_translate("YoyiJointWorkWindow", "下一页"))
        self.BodyLabel_8.setText(_translate("YoyiJointWorkWindow", "页"))
        self.featureJumpPb.setText(_translate("YoyiJointWorkWindow", "跳转"))
from qfluentwidgets import BodyLabel, ComboBox, PillPushButton, PillToolButton, PrimaryPushButton, PrimarySplitPushButton, PushButton, SpinBox, StrongBodyLabel, SwitchButton, TableWidget
import yoyirs_rc
