# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 330)
        Form.setMinimumSize(QtCore.QSize(500, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resources/logoLight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.StrongBodyLabel = StrongBodyLabel(Form)
        self.StrongBodyLabel.setProperty("pixelFontSize", 16)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.horizontalLayout_4.addWidget(self.StrongBodyLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_5 = BodyLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.userLE = LineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userLE.sizePolicy().hasHeightForWidth())
        self.userLE.setSizePolicy(sizePolicy)
        self.userLE.setMinimumSize(QtCore.QSize(0, 33))
        self.userLE.setClearButtonEnabled(True)
        self.userLE.setObjectName("userLE")
        self.verticalLayout_2.addWidget(self.userLE)
        self.label_6 = BodyLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.passwdLE = LineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwdLE.sizePolicy().hasHeightForWidth())
        self.passwdLE.setSizePolicy(sizePolicy)
        self.passwdLE.setMinimumSize(QtCore.QSize(0, 33))
        self.passwdLE.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwdLE.setClearButtonEnabled(True)
        self.passwdLE.setObjectName("passwdLE")
        self.verticalLayout_2.addWidget(self.passwdLE)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.showPswdChBox = CheckBox(Form)
        self.showPswdChBox.setChecked(False)
        self.showPswdChBox.setObjectName("showPswdChBox")
        self.verticalLayout_2.addWidget(self.showPswdChBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.rememberMeChBox = CheckBox(Form)
        self.rememberMeChBox.setChecked(True)
        self.rememberMeChBox.setObjectName("rememberMeChBox")
        self.verticalLayout_2.addWidget(self.rememberMeChBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.loginPB = PrimaryPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginPB.sizePolicy().hasHeightForWidth())
        self.loginPB.setSizePolicy(sizePolicy)
        self.loginPB.setObjectName("loginPB")
        self.verticalLayout_2.addWidget(self.loginPB)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CGGeoAnyLabeling"))
        self.StrongBodyLabel.setText(_translate("Form", "登录多人协同勾画系统"))
        self.label_5.setText(_translate("Form", "用户名"))
        self.userLE.setPlaceholderText(_translate("Form", "请输入您的姓名首字母"))
        self.label_6.setText(_translate("Form", "密码"))
        self.passwdLE.setPlaceholderText(_translate("Form", "请输入您的密码"))
        self.showPswdChBox.setText(_translate("Form", "密码可见"))
        self.rememberMeChBox.setText(_translate("Form", "记住密码"))
        self.loginPB.setText(_translate("Form", "登录"))
from qfluentwidgets import BodyLabel, CheckBox, LineEdit, PrimaryPushButton, StrongBodyLabel
import yoyirs_rc
