# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(400, 300)
        LoginDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame = QtWidgets.QFrame(LoginDialog)
        self.frame.setGeometry(QtCore.QRect(9, 9, 382, 282))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.dev_btn = SwitchButton(self.frame)
        self.dev_btn.setObjectName("dev_btn")
        self.horizontalLayout.addWidget(self.dev_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.TitleLabel = TitleLabel(self.frame)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appid_lineEdit = LineEdit(self.frame_2)
        self.appid_lineEdit.setObjectName("appid_lineEdit")
        self.verticalLayout_2.addWidget(self.appid_lineEdit)
        self.appid_lineEdit_2 = LineEdit(self.frame_2)
        self.appid_lineEdit_2.setObjectName("appid_lineEdit_2")
        self.verticalLayout_2.addWidget(self.appid_lineEdit_2)
        self.login_pushButton = PrimaryPushButton(self.frame_2)
        self.login_pushButton.setObjectName("login_pushButton")
        self.verticalLayout_2.addWidget(self.login_pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.dev_btn.setWhatsThis(_translate("LoginDialog", "<html><head/><body><p>ds </p></body></html>"))
        self.dev_btn.setText(_translate("LoginDialog", "dev"))
        self.dev_btn.setOnText(_translate("LoginDialog", "pre"))
        self.dev_btn.setOffText(_translate("LoginDialog", "dev"))
        self.TitleLabel.setText(_translate("LoginDialog", "登录"))
        self.appid_lineEdit.setPlaceholderText(_translate("LoginDialog", "用户名"))
        self.appid_lineEdit_2.setPlaceholderText(_translate("LoginDialog", "用户名"))
        self.login_pushButton.setText(_translate("LoginDialog", "登录"))
from qfluentwidgets import LineEdit, PrimaryPushButton, SwitchButton, TitleLabel
