# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapToolInputAttr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(421, 381)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 411, 311))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 309))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 391, 291))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.attrsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.attrsLayout.setContentsMargins(0, 0, 0, 0)
        self.attrsLayout.setObjectName("attrsLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.add = QtWidgets.QPushButton(self.dockWidgetContents)
        self.add.setGeometry(QtCore.QRect(100, 320, 75, 23))
        self.add.setObjectName("add")
        self.cancel = QtWidgets.QPushButton(self.dockWidgetContents)
        self.cancel.setGeometry(QtCore.QRect(240, 320, 75, 23))
        self.cancel.setObjectName("cancel")
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.add.setText(_translate("DockWidget", "新增"))
        self.cancel.setText(_translate("DockWidget", "取消"))
