# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\measureDistanceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_measureDistanceDialog(object):
    def setupUi(self, measureDistanceDialog):
        measureDistanceDialog.setObjectName("measureDistanceDialog")
        measureDistanceDialog.resize(347, 401)
        self.verticalLayout = QtWidgets.QVBoxLayout(measureDistanceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.baseInCartesianCb = CheckBox(measureDistanceDialog)
        self.baseInCartesianCb.setChecked(True)
        self.baseInCartesianCb.setObjectName("baseInCartesianCb")
        self.baseModeButtonGroup = QtWidgets.QButtonGroup(measureDistanceDialog)
        self.baseModeButtonGroup.setObjectName("baseModeButtonGroup")
        self.baseModeButtonGroup.addButton(self.baseInCartesianCb)
        self.horizontalLayout_15.addWidget(self.baseInCartesianCb)
        self.baseInEllipsoidCb = CheckBox(measureDistanceDialog)
        self.baseInEllipsoidCb.setChecked(False)
        self.baseInEllipsoidCb.setObjectName("baseInEllipsoidCb")
        self.baseModeButtonGroup.addButton(self.baseInEllipsoidCb)
        self.horizontalLayout_15.addWidget(self.baseInEllipsoidCb)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.BodyLabel_2 = BodyLabel(measureDistanceDialog)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_17.addWidget(self.BodyLabel_2)
        self.decimalPrecisionSpinBox = SpinBox(measureDistanceDialog)
        self.decimalPrecisionSpinBox.setMinimum(1)
        self.decimalPrecisionSpinBox.setMaximum(8)
        self.decimalPrecisionSpinBox.setProperty("value", 4)
        self.decimalPrecisionSpinBox.setObjectName("decimalPrecisionSpinBox")
        self.horizontalLayout_17.addWidget(self.decimalPrecisionSpinBox)
        self.BodyLabel_3 = BodyLabel(measureDistanceDialog)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_17.addWidget(self.BodyLabel_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.autoTransUnitCheckBox = CheckBox(measureDistanceDialog)
        self.autoTransUnitCheckBox.setObjectName("autoTransUnitCheckBox")
        self.verticalLayout.addWidget(self.autoTransUnitCheckBox)
        self.ListWidget = ListWidget(measureDistanceDialog)
        self.ListWidget.setObjectName("ListWidget")
        self.verticalLayout.addWidget(self.ListWidget)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.BodyLabel = BodyLabel(measureDistanceDialog)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_14.addWidget(self.BodyLabel)
        self.totalLE = LineEdit(measureDistanceDialog)
        self.totalLE.setReadOnly(True)
        self.totalLE.setObjectName("totalLE")
        self.horizontalLayout_14.addWidget(self.totalLE)
        self.unitCb = ComboBox(measureDistanceDialog)
        self.unitCb.setObjectName("unitCb")
        self.horizontalLayout_14.addWidget(self.unitCb)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.clearPb = PushButton(measureDistanceDialog)
        self.clearPb.setObjectName("clearPb")
        self.verticalLayout.addWidget(self.clearPb)

        self.retranslateUi(measureDistanceDialog)
        QtCore.QMetaObject.connectSlotsByName(measureDistanceDialog)

    def retranslateUi(self, measureDistanceDialog):
        _translate = QtCore.QCoreApplication.translate
        measureDistanceDialog.setWindowTitle(_translate("measureDistanceDialog", "Measure Parameter Settings"))
        self.baseInCartesianCb.setText(_translate("measureDistanceDialog", "Based on Cartesian Crs"))
        self.baseInEllipsoidCb.setText(_translate("measureDistanceDialog", "Based on Ellipsoid"))
        self.BodyLabel_2.setText(_translate("measureDistanceDialog", "Decimal Point Retained"))
        self.BodyLabel_3.setText(_translate("measureDistanceDialog", "places"))
        self.autoTransUnitCheckBox.setText(_translate("measureDistanceDialog", "Automatic Unit Conversion"))
        self.BodyLabel.setText(_translate("measureDistanceDialog", "Total"))
        self.clearPb.setText(_translate("measureDistanceDialog", "Clear"))
from qfluentwidgets import BodyLabel, CheckBox, ComboBox, LineEdit, ListWidget, PushButton, SpinBox
import yoyirs_rc
