# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\measureAreaDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_measureAreaDialog(object):
    def setupUi(self, measureAreaDialog):
        measureAreaDialog.setObjectName("measureAreaDialog")
        measureAreaDialog.resize(347, 222)
        self.verticalLayout = QtWidgets.QVBoxLayout(measureAreaDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.baseInCartesianCb = CheckBox(measureAreaDialog)
        self.baseInCartesianCb.setChecked(True)
        self.baseInCartesianCb.setObjectName("baseInCartesianCb")
        self.baseModeButtonGroup = QtWidgets.QButtonGroup(measureAreaDialog)
        self.baseModeButtonGroup.setObjectName("baseModeButtonGroup")
        self.baseModeButtonGroup.addButton(self.baseInCartesianCb)
        self.horizontalLayout_15.addWidget(self.baseInCartesianCb)
        self.baseInEllipsoidCb = CheckBox(measureAreaDialog)
        self.baseInEllipsoidCb.setChecked(False)
        self.baseInEllipsoidCb.setObjectName("baseInEllipsoidCb")
        self.baseModeButtonGroup.addButton(self.baseInEllipsoidCb)
        self.horizontalLayout_15.addWidget(self.baseInEllipsoidCb)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.BodyLabel_2 = BodyLabel(measureAreaDialog)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_17.addWidget(self.BodyLabel_2)
        self.decimalPrecisionSpinBox = SpinBox(measureAreaDialog)
        self.decimalPrecisionSpinBox.setMinimum(1)
        self.decimalPrecisionSpinBox.setMaximum(8)
        self.decimalPrecisionSpinBox.setProperty("value", 4)
        self.decimalPrecisionSpinBox.setObjectName("decimalPrecisionSpinBox")
        self.horizontalLayout_17.addWidget(self.decimalPrecisionSpinBox)
        self.BodyLabel_3 = BodyLabel(measureAreaDialog)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_17.addWidget(self.BodyLabel_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.autoTransUnitCheckBox = CheckBox(measureAreaDialog)
        self.autoTransUnitCheckBox.setObjectName("autoTransUnitCheckBox")
        self.verticalLayout.addWidget(self.autoTransUnitCheckBox)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.totalLE = LineEdit(measureAreaDialog)
        self.totalLE.setReadOnly(True)
        self.totalLE.setObjectName("totalLE")
        self.horizontalLayout_14.addWidget(self.totalLE)
        self.unitCb = ComboBox(measureAreaDialog)
        self.unitCb.setObjectName("unitCb")
        self.horizontalLayout_14.addWidget(self.unitCb)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.clearPb = PushButton(measureAreaDialog)
        self.clearPb.setObjectName("clearPb")
        self.verticalLayout.addWidget(self.clearPb)

        self.retranslateUi(measureAreaDialog)
        QtCore.QMetaObject.connectSlotsByName(measureAreaDialog)

    def retranslateUi(self, measureAreaDialog):
        _translate = QtCore.QCoreApplication.translate
        measureAreaDialog.setWindowTitle(_translate("measureAreaDialog", "Measure Parameter Settings"))
        self.baseInCartesianCb.setText(_translate("measureAreaDialog", "Based on Cartesian Crs"))
        self.baseInEllipsoidCb.setText(_translate("measureAreaDialog", "Based on Ellipsoid"))
        self.BodyLabel_2.setText(_translate("measureAreaDialog", "Decimal Point Retained"))
        self.BodyLabel_3.setText(_translate("measureAreaDialog", "places"))
        self.autoTransUnitCheckBox.setText(_translate("measureAreaDialog", "Automatic Unit Conversion"))
        self.clearPb.setText(_translate("measureAreaDialog", "Clear"))
from qfluentwidgets import BodyLabel, CheckBox, ComboBox, LineEdit, PushButton, SpinBox
import yoyirs_rc
