# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rectangeMapToolDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(292, 54)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.attrCbLayout = QtWidgets.QVBoxLayout()
        self.attrCbLayout.setObjectName("attrCbLayout")
        self.comboBox = ComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.attrCbLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.attrCbLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "属性选择窗口"))
from qfluentwidgets import ComboBox
