# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\trans_attrDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DIYDialog(object):
    def setupUi(self, DIYDialog):
        DIYDialog.setObjectName("DIYDialog")
        DIYDialog.resize(835, 682)
        self.pushButton_6 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 30, 141, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 70, 141, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 110, 141, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 150, 31, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 150, 41, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_11.setGeometry(QtCore.QRect(90, 150, 71, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 190, 141, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 230, 141, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 270, 71, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_15.setGeometry(QtCore.QRect(90, 270, 71, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 310, 141, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 350, 141, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 390, 141, 31))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_19.setGeometry(QtCore.QRect(90, 430, 71, 31))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(DIYDialog)
        self.pushButton_20.setGeometry(QtCore.QRect(20, 430, 71, 31))
        self.pushButton_20.setObjectName("pushButton_20")

        self.retranslateUi(DIYDialog)
        QtCore.QMetaObject.connectSlotsByName(DIYDialog)

    def retranslateUi(self, DIYDialog):
        _translate = QtCore.QCoreApplication.translate
        DIYDialog.setWindowTitle(_translate("DIYDialog", "Dialog"))
        self.pushButton_6.setText(_translate("DIYDialog", "Create New Field"))
        self.pushButton_7.setText(_translate("DIYDialog", "New field name"))
        self.pushButton_8.setText(_translate("DIYDialog", "Field type"))
        self.pushButton_9.setText(_translate("DIYDialog", "Int"))
        self.pushButton_10.setText(_translate("DIYDialog", "Float"))
        self.pushButton_11.setText(_translate("DIYDialog", "String"))
        self.pushButton_12.setText(_translate("DIYDialog", "Field length"))
        self.pushButton_13.setText(_translate("DIYDialog", "Field precision"))
        self.pushButton_14.setText(_translate("DIYDialog", "OK"))
        self.pushButton_15.setText(_translate("DIYDialog", "Cancel"))
        self.pushButton_16.setText(_translate("DIYDialog", "Delete Field"))
        self.pushButton_17.setText(_translate("DIYDialog", "Update All"))
        self.pushButton_18.setText(_translate("DIYDialog", "Update Selected"))
        self.pushButton_19.setText(_translate("DIYDialog", "Show Selected"))
        self.pushButton_20.setText(_translate("DIYDialog", "Show All"))
