# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\VerifyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 321)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StrongBodyLabel = StrongBodyLabel(Dialog)
        self.StrongBodyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout.addWidget(self.StrongBodyLabel)
        self.StrongBodyLabel_2 = StrongBodyLabel(Dialog)
        self.StrongBodyLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.verticalLayout.addWidget(self.StrongBodyLabel_2)
        self.CaptionLabel = CaptionLabel(Dialog)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.verticalLayout.addWidget(self.CaptionLabel)
        self.questionLE = LineEdit(Dialog)
        self.questionLE.setReadOnly(True)
        self.questionLE.setObjectName("questionLE")
        self.verticalLayout.addWidget(self.questionLE)
        self.CaptionLabel_2 = CaptionLabel(Dialog)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.verticalLayout.addWidget(self.CaptionLabel_2)
        self.answerLE = LineEdit(Dialog)
        self.answerLE.setObjectName("answerLE")
        self.verticalLayout.addWidget(self.answerLE)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.okPb = PushButton(Dialog)
        self.okPb.setObjectName("okPb")
        self.horizontalLayout_20.addWidget(self.okPb)
        self.verticalLayout.addLayout(self.horizontalLayout_20)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Warning"))
        self.StrongBodyLabel.setText(_translate("Dialog", "请购买正版软件！"))
        self.StrongBodyLabel_2.setText(_translate("Dialog", "Please purchase genuine software!"))
        self.CaptionLabel.setText(_translate("Dialog", "本机标识码（Local machine ID code）"))
        self.CaptionLabel_2.setText(_translate("Dialog", "请输入本机序列码（Please enter the serial number）"))
        self.okPb.setText(_translate("Dialog", "OK"))
from qfluentwidgets import CaptionLabel, LineEdit, PushButton, StrongBodyLabel
