# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\webSampleProjectListDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1033, 595)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_3 = BodyLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_3.sizePolicy().hasHeightForWidth())
        self.BodyLabel_3.setSizePolicy(sizePolicy)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_2.addWidget(self.BodyLabel_3)
        self.projectNameFilterLE = LineEdit(Dialog)
        self.projectNameFilterLE.setObjectName("projectNameFilterLE")
        self.horizontalLayout_2.addWidget(self.projectNameFilterLE)
        self.BodyLabel = BodyLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel.sizePolicy().hasHeightForWidth())
        self.BodyLabel.setSizePolicy(sizePolicy)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_2.addWidget(self.BodyLabel)
        self.statusFilterCb = ComboBox(Dialog)
        self.statusFilterCb.setMinimumSize(QtCore.QSize(100, 0))
        self.statusFilterCb.setObjectName("statusFilterCb")
        self.horizontalLayout_2.addWidget(self.statusFilterCb)
        self.searchTb = PrimaryToolButton(Dialog)
        self.searchTb.setObjectName("searchTb")
        self.horizontalLayout_2.addWidget(self.searchTb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.projectTableWidget = TableWidget(Dialog)
        self.projectTableWidget.setObjectName("projectTableWidget")
        self.projectTableWidget.setColumnCount(0)
        self.projectTableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.projectTableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.projectsTotalLabel = StrongBodyLabel(Dialog)
        self.projectsTotalLabel.setObjectName("projectsTotalLabel")
        self.horizontalLayout_3.addWidget(self.projectsTotalLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lastPb = PrimaryPushButton(Dialog)
        self.lastPb.setObjectName("lastPb")
        self.horizontalLayout_3.addWidget(self.lastPb)
        self.nextPb = PrimaryPushButton(Dialog)
        self.nextPb.setObjectName("nextPb")
        self.horizontalLayout_3.addWidget(self.nextPb)
        self.jumpPb = PrimaryPushButton(Dialog)
        self.jumpPb.setObjectName("jumpPb")
        self.horizontalLayout_3.addWidget(self.jumpPb)
        self.pageIndexSpinBox = SpinBox(Dialog)
        self.pageIndexSpinBox.setObjectName("pageIndexSpinBox")
        self.horizontalLayout_3.addWidget(self.pageIndexSpinBox)
        self.BodyLabel_7 = BodyLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_7.sizePolicy().hasHeightForWidth())
        self.BodyLabel_7.setSizePolicy(sizePolicy)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.horizontalLayout_3.addWidget(self.BodyLabel_7)
        self.pageSizeComboBox = ComboBox(Dialog)
        self.pageSizeComboBox.setObjectName("pageSizeComboBox")
        self.horizontalLayout_3.addWidget(self.pageSizeComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.BodyLabel_3.setText(_translate("Dialog", "任务名称"))
        self.BodyLabel.setText(_translate("Dialog", "任务状态"))
        self.projectsTotalLabel.setText(_translate("Dialog", "1-10 共100个项目"))
        self.lastPb.setText(_translate("Dialog", "上一页"))
        self.nextPb.setText(_translate("Dialog", "下一页"))
        self.jumpPb.setText(_translate("Dialog", "跳转"))
        self.BodyLabel_7.setText(_translate("Dialog", "页"))
from qfluentwidgets import BodyLabel, ComboBox, LineEdit, PrimaryPushButton, PrimaryToolButton, SpinBox, StrongBodyLabel, TableWidget
