# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\shp_process_dialog\shpFixGeometryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shpFixGeoDialog(object):
    def setupUi(self, shpFixGeoDialog):
        shpFixGeoDialog.setObjectName("shpFixGeoDialog")
        shpFixGeoDialog.resize(442, 329)
        self.verticalLayout = QtWidgets.QVBoxLayout(shpFixGeoDialog)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 7)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_4 = CardWidget(shpFixGeoDialog)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel = BodyLabel(self.CardWidget_4)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_5.addWidget(self.BodyLabel)
        self.inputComboBox = ComboBox(self.CardWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputComboBox.sizePolicy().hasHeightForWidth())
        self.inputComboBox.setSizePolicy(sizePolicy)
        self.inputComboBox.setObjectName("inputComboBox")
        self.horizontalLayout_5.addWidget(self.inputComboBox)
        self.selectInputFilePB = ToolButton(self.CardWidget_4)
        self.selectInputFilePB.setObjectName("selectInputFilePB")
        self.horizontalLayout_5.addWidget(self.selectInputFilePB)
        self.verticalLayout.addWidget(self.CardWidget_4)
        self.CardWidget_3 = CardWidget(shpFixGeoDialog)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.CardWidget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BodyLabel_3 = BodyLabel(self.CardWidget_3)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_4.addWidget(self.BodyLabel_3)
        self.postNameLE = LineEdit(self.CardWidget_3)
        self.postNameLE.setObjectName("postNameLE")
        self.horizontalLayout_4.addWidget(self.postNameLE)
        self.verticalLayout.addWidget(self.CardWidget_3)
        self.CardWidget = CardWidget(shpFixGeoDialog)
        self.CardWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout.addWidget(self.BodyLabel_4)
        self.resLE = LineEdit(self.CardWidget)
        self.resLE.setObjectName("resLE")
        self.horizontalLayout.addWidget(self.resLE)
        self.selectSaveFilePB = ToolButton(self.CardWidget)
        self.selectSaveFilePB.setObjectName("selectSaveFilePB")
        self.horizontalLayout.addWidget(self.selectSaveFilePB)
        self.verticalLayout.addWidget(self.CardWidget)
        self.runPB = PushButton(shpFixGeoDialog)
        self.runPB.setObjectName("runPB")
        self.verticalLayout.addWidget(self.runPB)

        self.retranslateUi(shpFixGeoDialog)
        QtCore.QMetaObject.connectSlotsByName(shpFixGeoDialog)

    def retranslateUi(self, shpFixGeoDialog):
        _translate = QtCore.QCoreApplication.translate
        shpFixGeoDialog.setWindowTitle(_translate("shpFixGeoDialog", "Vector Fix Geo Parameter Settings"))
        self.BodyLabel.setText(_translate("shpFixGeoDialog", "Select Vector or Folder"))
        self.BodyLabel_3.setText(_translate("shpFixGeoDialog", "Input Result post"))
        self.BodyLabel_4.setText(_translate("shpFixGeoDialog", "Select Results Folder"))
        self.runPB.setText(_translate("shpFixGeoDialog", "OK"))
from qfluentwidgets import BodyLabel, CardWidget, ComboBox, LineEdit, PushButton, ToolButton
