# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\rsdm\ui\shp_process_dialog\shpIntersectionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shpIntersectDialog(object):
    def setupUi(self, shpIntersectDialog):
        shpIntersectDialog.setObjectName("shpIntersectDialog")
        shpIntersectDialog.resize(495, 284)
        self.verticalLayout = QtWidgets.QVBoxLayout(shpIntersectDialog)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 7)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_4 = CardWidget(shpIntersectDialog)
        self.CardWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel = BodyLabel(self.CardWidget_4)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_5.addWidget(self.BodyLabel)
        self.selectShpCb = ComboBox(self.CardWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectShpCb.sizePolicy().hasHeightForWidth())
        self.selectShpCb.setSizePolicy(sizePolicy)
        self.selectShpCb.setObjectName("selectShpCb")
        self.horizontalLayout_5.addWidget(self.selectShpCb)
        self.verticalLayout.addWidget(self.CardWidget_4)
        self.CardWidget_2 = CardWidget(shpIntersectDialog)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CardWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        self.selectIntersectionShpCb = ComboBox(self.CardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectIntersectionShpCb.sizePolicy().hasHeightForWidth())
        self.selectIntersectionShpCb.setSizePolicy(sizePolicy)
        self.selectIntersectionShpCb.setObjectName("selectIntersectionShpCb")
        self.horizontalLayout_2.addWidget(self.selectIntersectionShpCb)
        self.verticalLayout.addWidget(self.CardWidget_2)
        self.CardWidget_3 = CardWidget(shpIntersectDialog)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.CardWidget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BodyLabel_3 = BodyLabel(self.CardWidget_3)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_4.addWidget(self.BodyLabel_3)
        self.prefixLE = LineEdit(self.CardWidget_3)
        self.prefixLE.setObjectName("prefixLE")
        self.horizontalLayout_4.addWidget(self.prefixLE)
        self.verticalLayout.addWidget(self.CardWidget_3)
        self.CardWidget = CardWidget(shpIntersectDialog)
        self.CardWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout.addWidget(self.BodyLabel_4)
        self.resLE = LineEdit(self.CardWidget)
        self.resLE.setReadOnly(True)
        self.resLE.setObjectName("resLE")
        self.horizontalLayout.addWidget(self.resLE)
        self.selectSaveFilePB = ToolButton(self.CardWidget)
        self.selectSaveFilePB.setObjectName("selectSaveFilePB")
        self.horizontalLayout.addWidget(self.selectSaveFilePB)
        self.verticalLayout.addWidget(self.CardWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.runPB = PushButton(shpIntersectDialog)
        self.runPB.setObjectName("runPB")
        self.horizontalLayout_3.addWidget(self.runPB)
        self.cancelPB = PushButton(shpIntersectDialog)
        self.cancelPB.setObjectName("cancelPB")
        self.horizontalLayout_3.addWidget(self.cancelPB)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(shpIntersectDialog)
        QtCore.QMetaObject.connectSlotsByName(shpIntersectDialog)

    def retranslateUi(self, shpIntersectDialog):
        _translate = QtCore.QCoreApplication.translate
        shpIntersectDialog.setWindowTitle(_translate("shpIntersectDialog", "Vector Intersection Parameter Settings"))
        self.BodyLabel.setText(_translate("shpIntersectDialog", "Select Vector"))
        self.BodyLabel_2.setText(_translate("shpIntersectDialog", "Select Intersection Vector"))
        self.BodyLabel_3.setText(_translate("shpIntersectDialog", "Intersection Prefix(Can be Null)"))
        self.BodyLabel_4.setText(_translate("shpIntersectDialog", "Result Path"))
        self.runPB.setText(_translate("shpIntersectDialog", "OK"))
        self.cancelPB.setText(_translate("shpIntersectDialog", "Cancel"))
from qfluentwidgets import BodyLabel, CardWidget, ComboBox, LineEdit, PushButton, ToolButton
import yoyirs_rc
